### ISSUE TITLE
[BUG] Pymongo 4.9 is not supported

### ISSUE THREAD

**Issue by kewldan** [BeanieODM/beanie#1028]
**Describe the bug**
Using the motor library (dependency) will install the latest pymongo (4.9). Which is not yet supported in the library

```
Traceback (most recent call last):
  File "/usr/app/src/main.py", line 1, in <module>
    from beanie import init_beanie
  File "/usr/local/lib/python3.12/site-packages/beanie/__init__.py", line 1, in <module>
    from beanie.migrations.controllers.free_fall import free_fall_migration
  File "/usr/local/lib/python3.12/site-packages/beanie/migrations/controllers/free_fall.py", line 4, in <module>
    from beanie.migrations.controllers.base import BaseMigrationController
  File "/usr/local/lib/python3.12/site-packages/beanie/migrations/controllers/base.py", line 4, in <module>
    from beanie.odm.documents import Document
  File "/usr/local/lib/python3.12/site-packages/beanie/odm/documents.py", line 69, in <module>
    from beanie.odm.interfaces.aggregate import AggregateInterface
  File "/usr/local/lib/python3.12/site-packages/beanie/odm/interfaces/aggregate.py", line 7, in <module>
    from beanie.odm.queries.aggregation import AggregationQuery
  File "/usr/local/lib/python3.12/site-packages/beanie/odm/queries/aggregation.py", line 12, in <module>
    from motor.core import AgnosticCommandCursor
  File "/usr/local/lib/python3.12/site-packages/motor/core.py", line 30, in <module>
    from pymongo.cursor import _QUERY_OPTIONS, Cursor, RawBatchCursor
ImportError: cannot import name '_QUERY_OPTIONS' from 'pymongo.cursor' (/usr/local/lib/python3.12/site-packages/pymongo/cursor.py)
```

**To Reproduce**
```python
from beanie import init_beanie
```
`pip install beanie`

**Expected behavior**
normal library operation without ImportError

**Comment by kewldan** [comment]
Opened [PR](https://github.com/BeanieODM/beanie/pull/1027) with temporary fix (limit max version of pymongo)
