### ISSUE TITLE
decimal.Inexact: [<class 'decimal.Inexact'>]

### ISSUE THREAD

**Issue by vffuunnyy** [BeanieODM/beanie#1076]
**Describe the bug**
An exception is raised when attempting to create a document with a `Decimal` field. Specifically, the error occurs during BSON serialization of the `Decimal` value, resulting in `decimal.Inexact: [<class 'decimal.Inexact'>]`.

**To Reproduce**
```python
from decimal import Decimal

from beanie import init_beanie
from motor.motor_asyncio import AsyncIOMotorClient

from models import CoinUsdtModel

async def main():
    value = Decimal(8204491.822422388)

    client = AsyncIOMotorClient("...")
    await init_beanie(database=client.test_db, document_models=[CoinUsdtModel])

    await CoinUsdtModel(currency="BTC", market="example_market", price=value).create()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

**Expected behavior**
The document should be successfully created with the Decimal value stored without errors.

**Additional context**
The issue occurs during BSON serialization in the bson/decimal128.py module. It appears to be related to the handling of Decimal precision or context settings.

Python version: 3.12
Beanie version: 1.27.0
Motor version: 3.6.0
MongoDB version: 8.0.3

```
Traceback (most recent call last):
  File "/home/vfny/.../tests/decimal_tests.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/vfny/.../tests/decimal_tests.py", line 17, in main
    await CoinUsdtModel(currency="BTC", market="binance", price=value).create()
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/documents.py", line 391, in create
    return await self.insert(session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/actions.py", line 239, in wrapper
    result = await f(
             ^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/state.py", line 85, in wrapper
    result = await f(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/self_validation.py", line 19, in wrapper
    return await f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/documents.py", line 367, in insert
    get_dict(
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/dump.py", line 22, in get_dict
    return encoder.encode(document)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/encoder.py", line 129, in encode
    return self._encode_document(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/encoder.py", line 112, in _encode_document
    obj_dict[key] = sub_encoder.encode(value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/beanie/odm/utils/encoder.py", line 126, in encode
    return encoder(obj)
           ^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/bson/decimal128.py", line 218, in __init__
    self.__high, self.__low = _decimal_to_128(value)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vfny/.../.venv/lib/python3.12/site-packages/bson/decimal128.py", line 76, in _decimal_to_128
    value = ctx.create_decimal(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
decimal.Inexact: [<class 'decimal.Inexact'>]
```

**Comment by adeelsohailahmed** [comment]
Hi @vffuunnyy, could you please share where you are importing the `DecimalAnnotation` from?

**Comment by staticxterm** [comment]
Hi @vffuunnyy,
the problem is in how you use `Decimal`, as you pointed out; the issue is not in Beanie.
Beanie simply re-raises the exception being raised by bson/decimal128.py `ctx.create_decimal(value)` method call.
Please construct your `Decimal` object with the string variant of the floating point number:
```python
value = Decimal("8204491.822422388")
```
Lastly, for serialization/deserialization purposes, it is advised to use `beanie.DecimalAnnotation` instead of `decimal.Decimal`, which you are already doing in your Document model.
