### ISSUE TITLE
[BUG] Pydantic URLs broken in pydantic 2.10.3

### ISSUE THREAD

**Issue by slingshotvfx** [BeanieODM/beanie#1084]
**Describe the bug**
Due to [changes to URLs](https://pydantic.dev/articles/pydantic-v2-10-release#migrate-to-subclassing-instead-of-annotated-approach-for-pydantic-url-types) in `pydantic 2.10`, Pydantic URL types no longer work with Beanie.

**To Reproduce**
```python
from beanie import Document
from pydantic import AnyHttpUrl
from beanie import init_beanie, Document
from beanie.operators import Set
from motor.motor_asyncio import AsyncIOMotorClient
import asyncio


class TestModel(Document):
    url: AnyHttpUrl


async def init():
    client = AsyncIOMotorClient( )

    await init_beanie(database=client["DBName"], document_models=[TestModel])
    model = TestModel(url="http://www.example.com")
    await model.insert()
    await model.update(Set({TestModel.url: "http://www.example2.com"}))


if __name__ == "__main__":
    asyncio.run(init())

```

Stack trace:
```shell
Traceback (most recent call last):
  File "\dev\beanie_url_types.py", line 29, in <module>
    asyncio.run(init())
  File "\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "\dev\beanie_url_types.py", line 20, in init
    await model.insert()
  File "\.venv\Lib\site-packages\beanie\odm\actions.py", line 239, in wrapper
    result = await f(
             ^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\utils\state.py", line 89, in wrapper
    result = await f(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\utils\self_validation.py", line 19, in wrapper
    return await f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\documents.py", line 367, in insert
    get_dict(
  File ".venv\Lib\site-packages\beanie\odm\utils\dump.py", line 22, in get_dict
    return encoder.encode(document)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\utils\encoder.py", line 129, in encode
    return self._encode_document(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\utils\encoder.py", line 112, in _encode_document
    obj_dict[key] = sub_encoder.encode(value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\beanie\odm\utils\encoder.py", line 143, in encode
    raise ValueError(f"Cannot encode {obj!r}")
ValueError: Cannot encode AnyHttpUrl('http://www.example.com/')
```

**Expected behavior**
The model should be updated with the new URL.  This works fine in `pydantic 2.9`

**Additional context**
Pydantic's changes to URL types seems to have caused a lot of havoc, see here: https://github.com/pydantic/pydantic/issues/10910

**Comment by staticxterm** [comment]
Hi, thank you for the report, we were already aware of it. PRs are welcome.
For now, we are thinking of limiting the supported Pydantic v2 version range to <2.10.0 as there are too many issues in this minor version.

**Comment by mdaffad** [comment]
Hi, i want to contribute on this part and other breaking changes on the pydantic >2.10.0
