### ISSUE TITLE
[BUG] pydantic.errors.PydanticInvalidForJsonSchema occured when APIRouter's response_model has PydanticObjectId Field

### ISSUE THREAD

**Issue by hagd0520** [BeanieODM/beanie#1087]
**Describe the bug**
pydantic.errors.PydanticInvalidForJsonSchema occured when APIRouter's response_model has PydanticObjectId Field
It occurs to beanie 1.28

**To Reproduce**
```python
    @sample_router.post("$", response_model=PydanticObjectId)
    async def create_sample():
        sample = await self.sample_service.create()
        return sample.id
```

**Stack trace**
```
Traceback (most recent call last):
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\fastapi\applications.py", line 1009, in openapi
    return JSONResponse(self.openapi())
                        ~~~~~~~~~~~~^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\fastapi\applications.py", line 981, in openapi
    self.openapi_schema = get_openapi(
                          ~~~~~~~~~~~^
        title=self.title,
        ^^^^^^^^^^^^^^^^^
    ...<11 lines>...
        separate_input_output_schemas=self.separate_input_output_schemas,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\fastapi\openapi\utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
                                 ~~~~~~~~~~~~~~~^
        fields=all_fields,
        ^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        separate_input_output_schemas=separate_input_output_schemas,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\fastapi\_compat.py", line 229, in get_definitions
    field_mapping, definitions = schema_generator.generate_definitions(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        inputs=inputs
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 379, in generate_definitions
    self.generate_inner(schema)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 37, in __call__
    return self.handler(core_schema)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 527, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\beanie\odm\fields.py", line 178, in __get_pydantic_json_schema__
    json_schema = handler(schema)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 37, in __call__
    return self.handler(core_schema)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 511, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 1263, in json_or_python_schema
    return self.generate_inner(schema['json_schema'])
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 37, in __call__
    return self.handler(core_schema)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 511, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 1014, in function_plain_schema
    return self.handle_invalid_for_json_schema(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        schema, f'core_schema.PlainValidatorFunctionSchema ({schema["function"]})'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hagd0\AppData\Local\pypoetry\Cache\virtualenvs\ceep-api-B8fTZraC-py3.13\Lib\site-packages\pydantic\json_schema.py", line 2185, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'with-info', 'function': <bound method PydanticObjectId.validate of <class 'beanie.odm.fields.PydanticObjectId'>>})
```

**Comment by staticxterm** [comment]
Hi @hagd0520, thank you for the report.
This issue will be solved by #1080.

**Comment by charlesdzadu** [comment]
Hi Guys.  I'm facing the same issue.

**Comment by microyahoo** [comment]
I met same issue too.

**Comment by RitinaADM** [comment]
I met same issue too.

**Comment by pharmac1st** [comment]
Just hit this as well

```
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'with-info', 'function': <bound method PydanticObjectId.validate of <class 'beanie.odm.fields.PydanticObjectId'>>})

For further information visit https://errors.pydantic.dev/2.10/u/invalid-for-json-schema
```

**Comment by staticxterm** [comment]
Hi @pharmac1st,

could you please provide some more information about your environment, like which Pydantic version are you using?
If using v1, this may still be an issue and Roman himself suggests doing something like this (as FastAPI defines their own encoders, which are outside of Beanie's control and can't hook into them the same way as it does with Pydantic): https://github.com/BeanieODM/beanie/issues/621#issuecomment-1646427312

**Comment by a3963969** [comment]
fix: resolve PydanticObjectId JSON Schema generation issue

Problem:
- FastAPI's OpenAPI schema generation fails with PydanticObjectId fields
- Error: "Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema"
- This is due to compatibility issues between Beanie ODM and Pydantic v2

Solution:
- Replace PydanticObjectId with str type for MongoDB _id fields
- Use Field with alias="_id" to maintain MongoDB compatibility
- Example: id: Optional[str] = Field(default=None, alias="_id")

**Comment by dantetemplar** [comment]
> Hi @pharmac1st,
> 
> could you please provide some more information about your environment, like which Pydantic version are you using? If using v1, this may still be an issue and Roman himself suggests doing something like this (as FastAPI defines their own encoders, which are outside of Beanie's control and can't hook into them the same way as it does with Pydantic): [#621 (comment)](https://github.com/BeanieODM/beanie/issues/621#issuecomment-1646427312)

It can't be related to encoders as it is occurs during mode="validation" step (route arguments).

**Comment by dantetemplar** [comment]
Issue related to that commit: https://github.com/BeanieODM/beanie/commit/66d78bff52c0348b64a9cc7ea019d204eb0974a4

**Comment by dantetemplar** [comment]
I found workaround, plz check it 🐍

**Comment by hagd0520** [comment]
This prob is solved from 1.29.0 ver. tyvm.

**Comment by ixavierone** [comment]
It seems that Beanie 1.29.0 was not enough. After upgrading to the newer version of Pydantic V2 (for me, from 2.8.2 to 2.10.6), it worked fine！

**Comment by carminoplata** [comment]
Hi, 

I’m facing with this issue in Beanie 1.29.0 and Pydantic 2.11.0. I didn’t understand if it has been solved but not released or it’s still under discussion.

Could you provide any feedback or a possible solution in the meantime?

Thanks in advance.

**Comment by staticxterm** [comment]
@carminoplata please open a new issue with attached runnable script that reproduces your issue. Thanks
