### ISSUE TITLE
[BUG] Weird `TypeError` when calling `init_beanie` using `dict` instead of `Dict` in module

### ISSUE THREAD

**Issue by ivan-gj** [BeanieODM/beanie#824]
Using Python 3.10, one is expected to essentially not use `Dict` anymore, and simply utilise `dict`. This is also true with many other types such as `tuple`, etc.

 This, tho, makes `beanie` raise a `TypeError` if such `dict` usage is done at the module level of one of the documents input to `init_beanie`. 

**To Reproduce**
```python
import asyncio
from typing import Any

from beanie import Document, init_beanie
from motor.motor_asyncio import AsyncIOMotorClient

DictStrAny = dict[str, Any]


class Thing(Document):
    thing: DictStrAny

    class Settings:
        name = "things"


async def main():
    client = AsyncIOMotorClient("mongodb://localhost:27017")

    await init_beanie(database=client["test_db"], document_models=[Thing])


if __name__ == "__main__":
    asyncio.run(main())

```

**Expected behaviour**

Technically, nothing wrong has been done here, but the program crashes with the following: 
```
Traceback (most recent call last):
  [...]
  File "[...]/beanie_crash_pydantic_v2.py", line 20, in main
    await init_beanie(database=client["test_db"], document_models=[Thing])
  File "[...]/.cache/pypoetry/virtualenvs/algo-db-manager-C0jUbCoT-py3.10/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 754, in init_beanie
    await Initializer(
  File "[...]/.cache/pypoetry/virtualenvs/algo-db-manager-C0jUbCoT-py3.10/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 121, in __init__
    self.fill_docs_registry()
  File "[...]/.cache/pypoetry/virtualenvs/algo-db-manager-C0jUbCoT-py3.10/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 137, in fill_docs_registry
    if inspect.isclass(obj) and issubclass(obj, BaseModel):
  File "[...]/.conda/envs/python310/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Additional context**
Using:
- `pydantic` v2.5.3
- `beanie` v1.24.0
- `python` v3.10.

---

**Current workaround**

Current workaround is to either come back to use capital `Dict` (or equivalents) in those kinds of definitions... which goes technically against current style guides, or avoid using this kind of auxiliary definitions at all.

**Comment by roman-right** [comment]
Hi @ivan-gj ,
Thank you for the catch!

**Comment by staticxterm** [comment]
Confirmed reproduced under Python 3.10 only. Would upgrading to a newer Python version work for you?
```bash
$ python py310_repro.py 
Traceback (most recent call last):
  File "C:\Users\...\Projects\beanie-test-migrations\py310_repro.py", line 24, in <module>
    asyncio.run(main())
  File "C:\Users\...\.pyenv\pyenv-win\versions\3.10.5\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\...\.pyenv\pyenv-win\versions\3.10.5\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\...\Projects\beanie-test-migrations\py310_repro.py", line 20, in main
    await init_beanie(database=client["test_db"], document_models=[Thing])
  File "C:\Users\...\Projects\beanie-test-migrations\.venv\lib\site-packages\beanie\odm\utils\init.py", line 782, in init_beanie       
    await Initializer(
  File "C:\Users\...\Projects\beanie-test-migrations\.venv\lib\site-packages\beanie\odm\utils\init.py", line 126, in __init__
    self.fill_docs_registry()
  File "C:\Users\...\Projects\beanie-test-migrations\.venv\lib\site-packages\beanie\odm\utils\init.py", line 142, in fill_docs_registry
    if inspect.isclass(obj) and issubclass(obj, BaseModel):
  File "C:\Users\...\.pyenv\pyenv-win\versions\3.10.5\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```
Interestingly, the same is not reproduced if the document model is typed as:
```python
class Thing(Document):
    thing: dict[str, Any]

    class Settings:
        name = "things"
```
By not using the type alias.

The issue is caused since `DictStrAny` is not a subclass of a `pydantic.BaseModel` which Beanie is expecting but rather a `typing.GenericAlias` type and so it fails.
For the fix, maybe we could try wrapping the critical section in a try-except, or by doing some different check. Example:
```python
    def fill_docs_registry(self):
        for model in self.document_models:
            module = inspect.getmodule(model)
            members = inspect.getmembers(module)
            for name, obj in members:
                try:
                    if inspect.isclass(obj) and issubclass(obj, BaseModel):
                        DocsRegistry.register(name, obj)
                except TypeError:
                    pass
```
Or we could replace the `issubclass` call with the `lenient_issubclass()` method from Pydantic: https://github.com/pydantic/pydantic/pull/2392
To fix this under Python 3.10.

**Comment by staticxterm** [comment]
I am not able to reproduce this anymore on Python 3.10.* and with Pydantic >=2.11.0. It seems something was fixed there.
Still, I would argue that we could and should fix this issubclass() check on our side, to guard against it.
